name: 'Stacc Publish'
author: 'Stacc'
description: Publish an app to the Stacc Registry
inputs:
  version:
    description: publishing version
    required: true
  clientId:
    description: client id
    required: true
  clientSecret:
    description: client secret
    required: true
  moduleDir:
    description: directory where the module is located
    required: false
    default: "."
runs:
  using: docker
  image: Dockerfile
  env:
    STACC_CLIENT_ID: ${{ inputs.clientId }}
    STACC_CLIENT_SECRET: ${{ inputs.clientSecret }}
    VERSION: ${{ inputs.version }}
    MODULE_DIR: ${{ inputs.moduleDir }}
